function chooseOption() {
	var option = [
	'Chamar uma estranha de "mãe" uma vez por dia',
	'Não conseguir respirar pelo nariz',
	'Só pode ficar parado ou correr a toda velocidade',
	'Espirrar toda vez que beijar alguém',
	'Mandar mensagem de "SOCORRO" pra sua mãe e sumir por um mês',
	'Lutar com um avestruz até a morte',
	'Sempre ter voz de quem inalou gás hélio',
	'Sempre sentir que você não dormiu na última noite',
	'Ter toda sua comida mastigada por outra pessoa antes de comer',
	'Usar aparelho com freio de burro pro resto da vida',
	'Divulgar seu contato e endereço pra todos os Telemarketings e não poder bloquear',
	'Sempre comer alho imediatamente depois de escovar os dentes',
	'Toda vez que apertar a mão de alguém, tentar forçar por pelo menos 30 segundos',
	'Responder sempre honestamente tudo que te perguntarem',
	'Ter todas as suas doenças tratadas por um médico do século XII',
	'Perder um dente por mês até ficar sem nada',
	'Nunca mais falar com a última pessoa que você mandou mensagem',
	'Inverter doce e salgado no paladar',
	'Usar caixa de areia sempre que precisar ir no banheiro',
	'Hibernar por 4 meses do ano',
	'Viver sem nunca mais ouvir música',
	'Sentir que gota de chuva tem peso de uma bola de tênis',
	'Eterna sensação de querer espirrar mas não conseguir',
	'Chutar o dedinho do pé na quina sempre que levantar',
	'Liberar seu histórico de conversas no whatsapp publicamente pra sempre',
	'Morar no 20º andar de um prédio. Mas não tem elevador',
	'Perder seus dois dedões das mãos',
	'Ser alérgico a luz direta do sol',
	'Ter uma alérgia mortal de todo mundo que você convive por mais de um ano',
	'Sempre ter alguém no telefone quando enquanto você usa o banheiro',
	'Ter um nariz de invertido (narina pra cima)',
	'Nunca mais tocar outra pessoa',
	'Ter braços no lugar das pernas',
	'Só poder tomar banho com temperatura congelante',
	'Só poder tomar banho com temperatura escaldante'
	'Ter pessoas aleatórias vaiando e cuspindo em você quando sair na rua',
	'Mergulhar todas as suas comidas num pote de água antes de comer',
	'Sempre se atrasar 1 hora pra tudo',
	'Sempre usar roupa e capacete de ciclista',
	'Ter olhos que funcionam normalmente, mas são brancos',
	'Ser obrigado a roubar de todo potinho de doação e gorjeta',
	'Só poder andar pra se transportar pra qualquer lugar',
	'Ser alérgico a toda comida e bebida que começa com “C” ou “M”',
	'Tomar 5 xícaras de espresso a cada refeição',
	'Acordar todo dia com um balde de gelo na cara',
	'Sempre falar de você na terceira pessoa',
	'Seus olhos só podem funcionar durante a noite',
	'Não conseguir atravessar a rua sem segurar a mão de alguém',
	'Tentar bater na cara das pessoas sempre que elas te derem bom dia',
	'Beber toda a água da privada sem usar as mãos',
	'Falar com sotaque falso o tempo todo e todo mundo sabe que é falso',
	'Seu quarto ser infestado por todos os insetos que você já matou',
	'Sempre andar saltitando pra onde for',
	'Não conseguir falar seu primeiro nome',
	'Perder todas as fotos que você já tirou',
	'Comer bola de pelo de um gato',
	'Só poder ficar parado ou correr a toda velocidade',
	'Só comer papinha de bebê sabor legumes',
	'Sempre falar na língua do P',
	'Passar todo fim de semana como monitor de buffet infantil sem ser pago',
	'Carregar uma tampa de bueiro em todo lugar que for',
	'Só comer whiskas sachê',
	'Só poder tomar água como bebida (sem café, sem cerveja etc...)',
	'Não poder falar a menos que esteja respondendo alguém',
	'Não ter os dois joelhos',
	'Fazer um video falando que ainda ama um(a) EX (com nome) e postar',
	'Demorar 1 minuto pra falar ou escrever seu nome',
	'Ter filhos e eles serem muito feios',
	'Se sentir sexualmente atraído por animais',
	'Perder uma semana de vida toda vez que transar',
	'Beijar a primeira pessoa que vê na rua todo dia',
	'Convencer todas as pessoas que você conhece que tem câncer e depois de 1 ano falar a verdade',
	'Por a mão num liquidificador ligado',
	'Sempre ligar pra mãe do parceiro antes e depois de transar pra avisar',
	'Fazer cirurgia, mas a anestesia te paralisa e não deixa falar apesar de você ainda estar sentindo tudo',
	'Sempre fazer um comentário racista no aniversário dos seus amigos',
	'Casar com alguém de um gênero que não te atrai',
	'Enfiar a cabeça numa fossa séptica',
	'Todo mundo que você conhece acreditar que você ficou com alguém da família',
	'Ser obrigado a matar uma pessoa todo ano',
	'Ter uma mosca morando no seu ouvido pelo resto da vida',
	'Doar metade do seu salário pro movimento anti-vacina',
	'Uma pessoa com covid cuspir na cara da sua mãe',
	'Tomar 5 shots de tequila todo dia antes do café da manhã',
	'Só pode sentar se estiver sem calça',
	'Não ter celular',
	'Apertar a bunda de todo mundo que te abraçar',
	'Sempre fazer metade do xixi na roupa',
	'Google publicar o seu histórico do navegador e buscas publicamente',
	'Só poder comer comida que fica no ralo da pia',
	'Vomitar sempre que te chamam',
	'Fazer xixi nas calças sempre que sentir dor (mais dor, mais xixi)',
	'Ter que dormir na rua uma vez por semana',
	'Dormir sempre na mesma cama que sua mãe',
	'Nunca mais viajar pra fora do seu estado',
	'Só poder usar o banheiro fora de casa',
	'Lamber a mão de todo mundo que cumprimentar',
	'Sentir o gosto de tudo pelas mãos',
	'Só poder usar roupas que já foram usadas por 3 dias',
	'Não poder mais mentir',
	'Passar todos os dias fantasiado de um personagem aleatório'
	];
	var op1 = Math.floor(option.length*Math.random());
	var op2 = Math.floor(option.length*Math.random());
	document.getElementById('card1_base').classList.add('rotation');
	document.getElementById('card2_base').classList.add('rotation');
	setTimeout(function() {
		document.getElementById('card1_txt').innerHTML = option[op1];
		document.getElementById('card2_txt').innerHTML = option[op2];
		document.getElementById('card1_base').classList.remove('rotation');
		document.getElementById('card2_base').classList.remove('rotation');
	}, 1000);
}